package com.ur.project.HotelApp;

import com.ur.project.HotelApp.model.Hotel;
import com.ur.project.HotelApp.model.Miasto;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BookingUI extends FormLayout {
    protected TextField bookNameTextField;
    protected TextField bookLastNameTextField;
    protected TextField bookEmailTextField;
    protected TextField bookTelNumTextField;
    protected ComboBox<Miasto> bookCityComboBox;
    protected ComboBox<Hotel> bookHotelComboBox;
    protected ComboBox<String> bookRoomType;
    protected ComboBox<String> bookBedConboBox;
    protected DateField bookFromDateField;
    protected DateField bookToDateField;
    protected Button bookSubmitButton;
    protected Button bookCancelButton;

    public BookingUI() {
        Design.read(this);
    }
}
