package com.ur.project.HotelApp;

import com.ur.project.HotelApp.model.Person;
import com.ur.project.HotelApp.model.Rezerwacja;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ManageUI extends HorizontalLayout {
    protected Label personLabel;
    protected Grid<Person> personGrid;
    protected Label rezerwacjaLabel;
    protected Grid<Rezerwacja> rezerwacjaGrid;
    protected Button cancelBookButton;

    public ManageUI() {
        Design.read(this);
    }
}
