package com.ur.project.HotelApp;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.TextField;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.Button;
import com.vaadin.ui.VerticalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Signup extends VerticalLayout {
    protected TextField signloginField1;
    protected PasswordField signpasswordField;
    protected PasswordField confpasswordField;
    protected TextField nameField;
    protected TextField lastnameField;
    protected TextField emailField;
    protected TextField telnumField;
    protected Button signconfButton;
    protected Button signcancelButton;

    public Signup() {
        Design.read(this);
    }
}
